
import { HeaderComponent } from '@/components/header'
import './globals.css'
import localFont from 'next/font/local'
import type { Metadata } from 'next'
import { FooterComponent } from '@/components/footer'
import ScrollProgressComponent from '@/components/scroolProgress'
import { wtGothic } from '@/fonts/constants'
import {ReactQueryProvider} from '@/components/providers/reactQueryProvider'
import {ToasterContext} from '@/components/providers/toasterProvider'

export const metadata: Metadata = {
  title: 'Florence',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <head>
        <link
          rel="icon"
          href="/images/icon/icon.png"
          sizes="any"
        />
      </head>
          <body className={`bg-custom-black max-w-[1440px] flex flex-col mx-auto ${wtGothic.className}`} >
            <ReactQueryProvider>
              <ToasterContext />
              <HeaderComponent />
              <main className='relative overflow-hidden'>
                  {children}
              </main>
              <FooterComponent />
            </ReactQueryProvider>
          </body>
    </html>
  )
}
