
import { HeaderComponent } from '@/components/header'
import './globals.css'
import localFont from 'next/font/local'
import type { Metadata } from 'next'
import { FooterComponent } from '@/components/footer'
import ScrollProgressComponent from '@/components/scroolProgress'

export const metadata: Metadata = {
  title: 'Florence',
  description: 'Generated by create next app',
}

const wtGothic = localFont({
  src: './fonts/WTGothic-Light.ttf',
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <head>
        <link
          rel="icon"
          href="/images/icon/icon.png"
          sizes="any"
        />
      </head>
          <body className={`bg-custom-black max-w-[1440px] flex flex-col mx-auto ${wtGothic.className}`} >
            <HeaderComponent />
            <main className='relative overflow-hidden'>
                {children}
            </main>
            <FooterComponent />
          </body>
    </html>
  )
}
