
import { HeaderComponent } from '@/components/header'
import './globals.css'
import localFont from 'next/font/local'
import type { Metadata } from 'next'
import { FooterComponent } from '@/components/footer'

export const metadata: Metadata = {
  title: 'Florence',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
          <body className={`bg-custom-black max-w-[1440px] flex flex-col mx-auto`}>
            <HeaderComponent />
            <main>
             {children}
            </main>
            <FooterComponent />
          </body>
    </html>
  )
}
